[options]
admin_passwd = admin
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = odoo

addons_path = /demo_odoo/odoo/addons,/demo_odoo/custom_addons

http_port = 8077
proxy_mode = False

log_level = info
logfile = /demo_odoo/odoo/odoo.log
